### ISSUE TITLE
多页应用如何使用ssr?

### ISSUE THREAD

**Issue by miyalee** [zeromake/my-vue-hackernews#1]
有多个app.js怎么处理呢？如何共用一个模版html？没有用router如何相应链接？

**Comment by zeromake** [comment]
多页的话，先说build的情况，[bundle, clientManifest](https://github.com/zeromake/my-vue-hackernews/blob/master/server.js#L43-L47), bundle, clientManifest变量需要在请求时进行获取根据url动态读取文件并生产renderer对象。记得缓存。因为没有router了直接异步获取数据放到vuex并设置到data上。详细实现方案和dev方案也有一些想法了。加我QQ详细聊：390720046

**Comment by zeromake** [comment]
@miyalee 怎么问了就没影了？

**Comment by miyalee** [comment]
算是解决了？模拟来router那段，根据URL判断加载哪个组件，感觉很黑科技，3q by the way!

**Comment by zeromake** [comment]
@miyalee 并不黑科技就是常见的后端渲染模式。。稍微做点后端的都会知道
